---
# TODO: specify version
- name: Install pip (Debian)
  apt:
    name: python-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Install pip (RedHat)
  yum:
    name: python-pip
    state: present
  when: ansible_os_family == "RedHat"
